# Sudoku solver Makefile.
#
# Copyright:	(c) 2010 Jacco van Schaik (jacco@jaccovanschaik.net)
#
# This software is distributed under the terms of the MIT license. See
# http://www.opensource.org/licenses/mit-license.php for details.

SUDOKU = sudoku.o

# Set to 1 to see progress.
DEBUG  = 0
CFLAGS = -g -Og -Wall -DDEBUG=$(DEBUG)

sudoku: $(SUDOKU)
	$(CC) $(CFLAGS) -o sudoku $(SUDOKU)

clean:
	rm -f *.o sudoku core sudoku.tgz

sudoku.tgz: clean
	tar cvf - `ls | grep -v sudoku.tgz` | gzip > sudoku.tgz

install: sudoku
	if [ ! -d $(INSTALL_BIN) ]; then mkdirhier $(INSTALL_BIN); fi
	cp sudoku $(INSTALL_BIN)

# Dependencies - generated by deps on Thu Apr  1 19:24:29 MEST 2010

sudoku.o: sudoku.c 
